apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-node-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: node-server.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: k8s-node-server
            port:
              number: 80
